/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zoid.localizacao.rivendel;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 *
 * @author Fabricio
 */
public class CidadeMapaView extends javax.swing.JFrame {

    private DefaultListModel listCidadeMapa;

    /**
     * Creates new form CidadeMapaView
     */
    public CidadeMapaView() {
        listCidadeMapa = new DefaultListModel();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Nome_Cidade_jtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Dono_local_jtxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tipo_local_jtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        qtd_lagos_jtxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        qtd_pontes_jtxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        qtd_habitantes_jtxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tamanho_cidade_jtxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        posX_jtxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        posY_jtxt = new javax.swing.JTextField();
        Inserir_btn = new javax.swing.JButton();
        Salvar_btn = new javax.swing.JButton();
        Carregar_btn = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Cadastrar Local"); // NOI18N

        jLabel1.setText("Nome do Local:");

        Nome_Cidade_jtxt.setToolTipText("");
        Nome_Cidade_jtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nome_Cidade_jtxtActionPerformed(evt);
            }
        });

        jLabel3.setText("Dono do Local:");

        Dono_local_jtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dono_local_jtxtActionPerformed(evt);
            }
        });

        jList1.setModel(this.listCidadeMapa);
        jScrollPane1.setViewportView(jList1);

        jLabel4.setText(" Local no Mapa");
        jLabel4.setToolTipText("");

        jLabel7.setText("Tipo de Local:");

        tipo_local_jtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_local_jtxtActionPerformed(evt);
            }
        });

        jLabel5.setText("Quantidade de Lagos:");

        jLabel6.setText("Quantidade de Pontes:");

        qtd_pontes_jtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtd_pontes_jtxtActionPerformed(evt);
            }
        });

        jLabel8.setText("Quantidade de Habitantes:");

        jLabel9.setText("Tamanho da Cidade:");

        jLabel10.setText("Posição X:");

        jLabel11.setText("Posição Y:");
        jLabel11.setToolTipText("");

        posY_jtxt.setToolTipText("");

        Inserir_btn.setText("Inserir");

        Salvar_btn.setText("Salvar");

        Carregar_btn.setText("Carregar");

        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        label1.setText("Cadastro para construção do Local");

        jButton1.setText("Deletar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Salvar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Carregar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_limpar))
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(52, 52, 52))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(qtd_lagos_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Nome_Cidade_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Dono_local_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipo_local_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(qtd_pontes_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(276, 276, 276)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tamanho_cidade_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtd_habitantes_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Inserir_btn)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(posX_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(posY_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Carregar_btn, Salvar_btn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome_Cidade_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo_local_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dono_local_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(qtd_lagos_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(qtd_pontes_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(qtd_habitantes_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tamanho_cidade_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(posX_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(posY_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Inserir_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Salvar_btn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Carregar_btn)
                        .addComponent(btn_limpar)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nome_Cidade_jtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nome_Cidade_jtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nome_Cidade_jtxtActionPerformed

    private void Dono_local_jtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dono_local_jtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dono_local_jtxtActionPerformed

    private void tipo_local_jtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_local_jtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_local_jtxtActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed

    }//GEN-LAST:event_btn_limparActionPerformed

    private void qtd_pontes_jtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtd_pontes_jtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtd_pontes_jtxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Carregar_btn;
    private javax.swing.JTextField Dono_local_jtxt;
    private javax.swing.JButton Inserir_btn;
    private javax.swing.JTextField Nome_Cidade_jtxt;
    private javax.swing.JButton Salvar_btn;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JTextField posX_jtxt;
    private javax.swing.JTextField posY_jtxt;
    private javax.swing.JTextField qtd_habitantes_jtxt;
    private javax.swing.JTextField qtd_lagos_jtxt;
    private javax.swing.JTextField qtd_pontes_jtxt;
    private javax.swing.JTextField tamanho_cidade_jtxt;
    private javax.swing.JTextField tipo_local_jtxt;
    // End of variables declaration//GEN-END:variables

    public void addElementoLista(Object o) {
        listCidadeMapa.addElement(o);

    }

    public JList<String> getjList1() {
        return jList1;
    }

    public void limparLista() {
        listCidadeMapa.clear();
    }

    public void setListenerInserir(ActionListener x) {
        Inserir_btn.addActionListener(x);
    }

    public void setListenerSalvar(ActionListener y) {
        Salvar_btn.addActionListener(y);
    }

    public void setListenerCarregar(ActionListener z) {
        Carregar_btn.addActionListener(z);
    }
    
    public void setListenerDeletar(ActionListener z) {
        jButton1.addActionListener(z);
    }
    

    public void setCarregardaLista(MouseListener z) {
        jList1.addMouseListener(z);
    }

    public void setLimpar(ActionListener k) {
        btn_limpar.addActionListener(k);
    }

    public String getDono_local_jtxt() {
        return Dono_local_jtxt.getText();
    }

    public String getNome_Cidade_jtxt() {
        return Nome_Cidade_jtxt.getText();
    }

    public double getPosX_jtxt() {
        return Double.parseDouble(posX_jtxt.getText());
    }

    public double getPosY_jtxt() {
        return Double.parseDouble(posY_jtxt.getText());
    }

    public int getQtd_habitantes_jtxt() {
        return Integer.parseInt(qtd_habitantes_jtxt.getText());
    }

    public int getQtd_lagos_jtxt() {
        return Integer.parseInt(qtd_lagos_jtxt.getText());
    }

    public int getQtd_pontes_jtxt() {
        return Integer.parseInt(qtd_pontes_jtxt.getText());
    }

    public double getTamanho_cidade_jtxt() {
        return Double.parseDouble(tamanho_cidade_jtxt.getText());
    }

    public String getTipo_local_jtxt() {
        return tipo_local_jtxt.getText();
    }

    public void setNome_Cidade_jtxt(String Nome_Cidade_jtxt) {
        this.Nome_Cidade_jtxt.setText(Nome_Cidade_jtxt);
    }

    public void setTipo_local_jtxt(String tipo_local_jtxt) {
        this.tipo_local_jtxt.setText(tipo_local_jtxt);
    }

    public void setDono_local_jtxt(String Dono_local_jtxt) {
        this.Dono_local_jtxt.setText(Dono_local_jtxt);
    }

    public void setPosX_jtxt(String posX_jtxt) {
        this.posX_jtxt.setText(posX_jtxt);
    }

    public void setPosY_jtxt(String posY_jtxt) {
        this.posY_jtxt.setText(posY_jtxt);
    }

    public void setQtd_habitantes_jtxt(String qtd_habitantes_jtxt) {
        this.qtd_habitantes_jtxt.setText(qtd_habitantes_jtxt);
    }

    public void setQtd_lagos_jtxt(String qtd_lagos_jtxt) {
        this.qtd_lagos_jtxt.setText(qtd_lagos_jtxt);
    }

    public void setQtd_pontes_jtxt(String qtd_pontes_jtxt) {
        this.qtd_pontes_jtxt.setText(qtd_pontes_jtxt);
    }

    public void setTamanho_cidade_jtxt(String tamanho_cidade_jtxt) {
        this.tamanho_cidade_jtxt.setText(tamanho_cidade_jtxt);
    }

    void limpar() {
        Dono_local_jtxt.setText(null);
        Nome_Cidade_jtxt.setText(null);
        posX_jtxt.setText(null);
        posY_jtxt.setText(null);
        qtd_habitantes_jtxt.setText(null);
        qtd_lagos_jtxt.setText(null);
        qtd_pontes_jtxt.setText(null);
        tamanho_cidade_jtxt.setText(null);
        tipo_local_jtxt.setText(null);

    }

}
